package com.ojassoft.astrosagecloud.util;

import java.util.HashMap;
import java.util.Map;

public class TitleConstants 
{
	public static final Map<String, String> titleMap = prepareMap();
	
	public static Map<String, String> prepareMap()
	{
		Map<String, String> hashMap = new HashMap<String, String>();
		hashMap.put("new_basicdetails.jsp","Avkahada Chakra, Favourable Points, Ghatak(Malefics)");
		hashMap.put("new_birth-details.jsp", "Avkahada Chakra, Favourable Points, Ghatak(Malefics)");
		hashMap.put("new_ashtaktable.jsp","AstroWeb Ashtakvarga Table");
		hashMap.put("new_astro-sketch.jsp","Astro Sketch");
		hashMap.put("new_babyname.jsp","Hindu Baby Names");
		hashMap.put("new_activation-page.jsp","Activation Page");
		hashMap.put("new_activation-problem.jsp","");
		hashMap.put("new_ascendant-prediction.jsp","Rising Ascendant Calculator");
		hashMap.put("new_bhavmadhya.jsp","AstroWeb Aspact on Bhav Madhya");
		hashMap.put("new_blog.jsp","Avkahada Chakra, Favourable Points, Ghatak(Malefics)");
		hashMap.put("new_career-horoscope.jsp","Career Horoscope");
		hashMap.put("new_chalittable.jsp","AstroWeb Chalit Table, Chalit Chart");
		hashMap.put("new_character-horoscope.jsp","Character Horoscope");
		hashMap.put("new_charantardasha1.jsp","AstroWeb Char Antardasha");
		hashMap.put("new_charantardasha2.jsp","AstroWeb Char Antardasha");
		hashMap.put("new_chart.jsp","AstroWeb Lagna & Chandra Charts");
		hashMap.put("new_confirmdata.jsp","Confirm Kundli Data");
		hashMap.put("new_dasha_phala.jsp","Dasha Phal Report/ Dasha Predictions");
		hashMap.put("new_disclaimer.jsp","Disclaimer");
		hashMap.put("new_download-kundli.jsp","download-kundli");
		hashMap.put("new_editchart.jsp","Edit Chart");
		hashMap.put("new_edituserprofile.jsp","Edit Profile");
		hashMap.put("new_friend.jsp","");
		hashMap.put("new_friendship.jsp","AstroWeb Friendship Charts-Permanent, Temporal, Panchadha");
		hashMap.put("new_gemstones-report.jsp","Gemology - precious stones, gem stone, lucky stone, birth stones - gem , gems");
		hashMap.put("new_getplanettoplanetaspectwestern.jsp","AstroWeb Aspect on KP Cusp");
		hashMap.put("new_jaminisystemkarakamsaswamsa.jsp","Jamini System Karakamsa Swamsa Kundli");
		hashMap.put("new_kalsarpa-yoga.jsp","Kal-Sarpa Yoga");
		hashMap.put("new_kpcusp.jsp","AstroWeb Aspect on KP Cusp");
		hashMap.put("new_kpplanetcusp.jsp","AstroWeb KP Planets & Cusps");
		hashMap.put("new_kpsignirp.jsp","AstroWeb KP Significators & Ruling Planets");
		hashMap.put("new_kptoday.jsp","Kp Today");
		hashMap.put("new_kundali-prediction.jsp","Hindi Predictions");
		hashMap.put("new_lagna-navamsa-jpeg-chart.jsp","Save Chart as image file (jpeg)");
		hashMap.put("new_lalkitab-debts-teva.jsp","Lalkitab Debts in Lalkitab");
		hashMap.put("new_lalkitab-prediction.jsp","LalKitab Prediction");
		hashMap.put("new_lalkitab-remedies-rules.jsp","Rules related to Lal Kitab Remedies");
		hashMap.put("new_lalkitab-teva.jsp","Teva in Lalkitab");
		hashMap.put("new_lalkitab-varshaphal-prediction.jsp","LalKitab Prediction");
		hashMap.put("new_lalkitabdasha.jsp","AstroWeb Lal Kitab Dasha");
		hashMap.put("new_lalkitabmonthchart.jsp","LalKitab Worksheet Page");
		hashMap.put("new_lalkitabvarshaphal.jsp","AstroWeb Lal Kitab Varshaphal");
		hashMap.put("new_lalkitabvarshaphalcharts.jsp","AstroWeb Lal Kitab Varshaphal Charts");
		hashMap.put("new_lalplanethouse.jsp","Lal Kitab Chart,Planet Houses,Soya,Kismat Jaganewala");
		hashMap.put("new_lkitabworksheet2.jsp","Lal Kitab Charts- Birth,Year,Month,Day,Hour,Minute,Second,Degree Chart");
		hashMap.put("new_login.jsp","Login");
		hashMap.put("new_loginwelcome.jsp","Login Welcome");
		hashMap.put("new_love-horoscope.jsp","Love Horoscope");
		hashMap.put("new_manglikdetails.jsp","AstroWeb Manglik Details");
		hashMap.put("new_matchmaking.jsp","Match Details");
		hashMap.put("new_matchmakingoutput.jsp","Match Details");
		hashMap.put("new_moon-sign.jsp","Moon signs");
		hashMap.put("new_nakshatra-report.jsp","Nakshatra calculator | Find your Nakshatra");
		hashMap.put("new_newchart.jsp","New Chart");
		hashMap.put("new_personalized-horoscope.jsp","Personalized Horoscope");
		hashMap.put("new_planetposition.jsp","AstroWeb Planetary Position, Lagna Chart");
		hashMap.put("new_planets-in-vedic-astrology.jsp","Planet: All about planets in Astrology");
		hashMap.put("new_prastharashtakvarga.jsp","AstroWeb Prastharashtakvarga Tables");
		hashMap.put("new_prediction1.jsp","Prediction- CHARACTER,CAREER,OCCUPATION,HEALTH");
		hashMap.put("new_prediction2.jsp","Prediction- CHARACTER,CAREER,OCCUPATION,HEALTH");
		hashMap.put("new_prediction3.jsp","Prediction- CHARACTER,CAREER,OCCUPATION,HEALTH");
		hashMap.put("new_rasi-calculator.jsp","Rasi Calculator, finding rasi sign, calculate rasi, rasi compatibility");
		hashMap.put("new_reg-activate-mail.jsp","");
		hashMap.put("new_reg-activation.jsp","");
		hashMap.put("new_sadesatireport.jsp","Shani Sade Sati");
		hashMap.put("new_service-order.jsp","Service Order");
		hashMap.put("new_services.jsp","Paid Services");
		hashMap.put("new_shadandbhav.jsp","AstroWeb ShadBala & BhavBala Tables");
		hashMap.put("new_shodashvargatable.jsp","Shodashvarga Rashi And Bhav Table");
		hashMap.put("new_signup.jsp","Sign Up");
		hashMap.put("new_svkgeneric.jsp","");
		hashMap.put("new_svkhora.jsp","Welcome TO The World Of Astrology");
		hashMap.put("new_svklagna.jsp","AstroWeb Shodashvarga Charts");
		hashMap.put("new_terms-conditions.jsp","Terms and Conditions");
		hashMap.put("new_transit-today.jsp","Transit Today Report");
		hashMap.put("new_transittodaychart.jsp","Transit Today Chart");
		hashMap.put("new_updateemailid.jsp","");
		hashMap.put("new_usermessage.jsp","User Message");
		hashMap.put("new_varshphalallpages.jsp","Tajik Varshphal Chart,Saham,Mudda Dasha,Panchadhikari");
		hashMap.put("new_varshphalprediction.jsp"," Horoscope");
		hashMap.put("new_vimshottaridasha.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd&sd1.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd&sd2.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd&sd3.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd&sd4.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd1.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad&pd2.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad&pd3.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad&pd4.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad&pd5.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmmd&ad.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad%26pd%26sd1.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad%26pd%26sd2.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad%26pd%26sd3.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad%26pd%26sd4.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad%26pd1.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad%26pd2.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad%26pd3.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_vmad%26pd4.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmad%26pd5.jsp","Vimshottari,Maha,Antar(bhukti),Pratyantar,Shookshma Dasha");
		hashMap.put("new_vmmd%26ad.jsp","AstroWeb Vimshottari Dasha");
		hashMap.put("new_westernsystem.jsp","Western Astrology System");
		hashMap.put("new_yoginidasha1.jsp","AstroWeb Yogini Dasha");
		hashMap.put("new_yoginidasha2.jsp","AstroWeb Yogini Dasha");
		hashMap.put("new_yoginidasha1.jsp","AstroWeb Yogini Dasha");
		hashMap.put("new_yoginidasha2.jsp","AstroWeb Yogini Dasha");
		hashMap.put("new_4-step.jsp","4-step");
		hashMap.put("new_cil.jsp","CIL");
		hashMap.put("new_kcil.jsp","KCIL");
		hashMap.put("new_nakshatra-nadi.jsp","Nakshatra Nadi");
		hashMap.put("new_planet-sign.jsp","Planet Sign (View 2)");
		hashMap.put("signcompatibility.jsp","Zodiac Sign Compatibility");
		hashMap.put("setmoonsign.jsp","Find Your Moon Sign(Rashi)");
		hashMap.put("sunsign.jsp","Sun Sign: Finding Your Sun Sign Compatibility");
		hashMap.put("porutham-result.jsp","Kundli Free Software Online | Janam Kundali");
		hashMap.put("namehoroscopematching.jsp","Horoscope Matching | Name Kundli Match");
		hashMap.put("lalkitab_page.jsp","Vedic astrology portal - Lalkitab");
		hashMap.put("new_jadi-report.jsp","Jadi Report");
		hashMap.put("new_rudraksha-report.jsp","Rudraksha Report");
		hashMap.put("new_yantra-report.jsp","Yantra Report");
		hashMap.put("new_healthindex.jsp","Health Index");
		hashMap.put("new_kp-system-cat.jsp","KP System");
		hashMap.put("new_matching-cat.jsp","Matching Horoscope");
		hashMap.put("new_lalkitab-cat.jsp","Lalkitab");
		hashMap.put("new_dasha-cat.jsp","Dasha");
		hashMap.put("new_calculation-cat.jsp","Calculations");
		hashMap.put("new_prediction-cat.jsp","Predictions");
		hashMap.put("new_hindi-mahadasha-phal.jsp","Dasha Phal Report / Dasha Predictions");
		hashMap.put("new_hindi-transit-today.jsp","Transit Today Report");
		hashMap.put("new_ishtdevata.jsp","Isht Devata");
		hashMap.put("new_user-key-points.jsp","Key Points For Your Kundli");
		hashMap.put("new_numerology-report.jsp","Numerology Report : Name Numerology With Date");
		hashMap.put("new_arudhapada.jsp","Arudha Chart : Arudha Pada");
		hashMap.put("new_upgrahchart.jsp","Upgrah Chart : Grah and Upgrah based kundli");
       return hashMap;
	}
}
