dev.url=jdbc:mysql://localhost:3306/astrosage?useUnicode=true&characterEncoding=UTF-8
dev.url1=jdbc:mysql://localhost:3306/atlas
dev.user_name=root
dev.password=ojassoft
cloud.url=jdbc:google:mysql://astrosage-967:astrosage/astrosage?user=root&useUnicode=true&characterEncoding=UTF-8
cloud.atlasurl=jdbc:google:mysql://astrosage-967:astrosage/atlas?user=root
cloud.user_name=ojasuser
cloud.password=Marksun#123
	