
THANKS_FOR_YOUR_FEEDBACK=Thanks for your feedback
MAIL_NOT_SEND=Feedback submission failed please try again.
IS_REQUIRED=is required.
EMPTY_NAME=Name
VALID_EMAIL=A valid Email
VALID_MESSAGE=A valid Message
NEM=Name
SUGGESTIONS=Suggestions

