FILE=File
SAVE_AND_SHARE=Save and share
CHART_MANAGEMENT=Chart Management
AND_KP=& KP
ENTER_GIRLS_BOYS_BIRTH_DETAIL=Match With Girl's / Boy's birth details
MATCH_WITH_SHARED_CHART=Match with shared chart
%>
