ALL_REPORTS=All Reports
PAGE=Page
SADE_SATI_REPORT=Sade Sati Report
ANNUAL_PREDICTIONS=Annual Prediction
LALKITAB=Lalkitab
NAKSHATRA_NADI=Nakshatra Nadi
SHAD_BALA_BHAV_BALA=Shad Bala & Bhav Bala
PRASTHARASHTAKVARGA=Prastharashtakvarga
