FREE_REPORTS=Select Free Report 
BIRTH_CHART_KUNDLI=Birth Chart/Kundli
PLANETARY_POSITIONS_AND_YOUR_CHART=Planetary position and your chart.
GUN_MILAN_WITH_YOUR_PARTNER=Guna milan with your partner
PERSONALIZED_HOROSCOPE_YEARLY=Personalized Horoscope
GET_YOUR_ANNUAL_PERSONALIZED_HOROSCOPE=Get your personalized annual horoscope for 2013.
KNOW_ABOUT_YOUR=Know about your
NATURE=Nature
ANDI=and
CAREER_NEW=Career.
KE_BAARE_ME= 
KNOW_PREDICTIONS_FOR_TODAY_BASED_ON_YOUR_BIRTH_CHART=Know predictions for today based on your birth chart. HOW_WILL_BE_2012_FOR_YOU_WHAT_GOOD_AND_BAD_YOU_CAN_EXPECT_IN_YEAR_2012					=How will be 2012 for you? What good and bad you can expect in year 2012?
 KNOW_LAL_KITAB_RED_BOOK_PREDICTIONS_REMEDIES_UPAY_FOR_YOUR_PROBLEMS						=Know Lal Kitab (Red Book) predictions, remedies & upay for your problems.
 WHICH_GEMSTONE_WILL_SUIT_YOU_WHICH_GEM_SHOULD_YOU_WEAR_HOW_TO_WEAR_GEMSTONE				=Which gemstone will suit you? Which gem should you wear? How to wear gemstone?
 DO_YOU_HAVE_MANGAL_DOSHA_WHAT_ARE_THE_REMEDIES_WHAT_ARE_THE_IMPACT_ON_YOUR_MARRIED_LIFE	=Do you have Mangal dosha? What are the remedies? What are the impact on your married life?
 KNOW_ABOUT_IMPACT_OF_SHANI_SADE_SATI_FOR_WHOLE_LIFE										=Know about impact of Shani Sade Sati for whole life.
 KNOW_ABOUT_IMPACT_OF_KALSHARP_DOSH_FOR_WHOLE_LIFE											=Know about impact of Kalsharp dosh for whole life.
 KNOW_ABOUT_RISE_AND_FALL_IN_LIFE_GOOD_AND_BAD_EVENTS_CHANGE_OF_TIME_IN_ADVANCE			=Know about rise and fall in life, good and bad events, change of time in advance.
 NAME_YOUR_BABY_ACCORDING_TO_VEDIC_ASTROLOGY_KNOW_HER_RASHI_AND_NAKSHATRA					=Name your baby according to Vedic Astrology? Know her Rashi and Nakshatra.
 HOW_DOES_POSITION_OF_CURRENT_PLANETS_IMPACT_YOU											=How does position of current planets impact you?
MISC=Misc. WHAT_DOES_YOUR=What does your
TELLS_ABOUT_YOU=tell about you.
