USER_ID_MIN_8_CHR=User Id (Min 8 Characters)
LOGIN_H=Login
SIGN_UP_TITLE=Sign Up
MOBILE_SHOULD_NOT_BE_BLANK=Mobile No. should not be blank.
CHART_NAME_IS_REQUIRED_IF_IT_IS_SAVED_AS_SHARED=Chart Name is required if it is saved as shared.
PLEASE_TRY_AGAIN_TO_SIGN_UP_WITH_DIFFERENT_USER_ID=Please try again to sign up with different User Id.
ENTER_USER_ID_WITH_WHOM_YOU_WANT_TO_SHARE_CHART=Enter User Id with whom you want to share chart
YOU_CAN_NOT_SHARE_CHART_WITH_YOUR_OWN_USER_ID=You can not share chart with your own User Id
USER_ID_CAN_NOT_BE_BLANK=User Id can not be blank
SESSION_EXPIRED_PLEASE_LOGIN_AGAIN=Your session expired. Please login again.
SHARE_CHART_REQUEST_HAS_BEEN_SENT_SUCCESSFULLY=Share Chart request has been sent successfully
SHARE_CHART_REQUEST_NOT_SENT_PLEASE_TRY_AGAIN=Share Chart request not sent, Please try again
PLEASE_LOGIN_BEFORE_SHARING_A_CHART=Please login before sharing a chart
PLEASE_SAVE_CHART_FIRST_BEFORE_SHARING_A_CHART=Please save chart first before sharing a chart
USER_ID_DOES_NOT_EXIST_PLEASE_TRY_WITH_DIFFERENT_USER_ID=User Id does not exist, Please try with different User Id
PLEASE_ENTER=Please enter
Fill_HINDI=.
CHOOSE_CHART_VISIBILITY=Choose Chart visibility
ALERT=Alert 
CHART_NAME_CAN_NOT_BE_START_WITH_DIGIT=Chart name can not be start with digit or hyphen (-)
CHART_NAME_CAN_NOT_BE_END_HYPHEN=Chart name can not be end with hyphen (-)
PLEASE_ENTER_VALID_CHART_NAME=Please enter valid chart name
CHART_NAME_CAN_BE_GVN_AS_COMBI_ALPHB_DIGITS=Chart name can be given as a combination of alphabets, digits and hyphen (-) only
ADD_TAGS=Add Tags
