PLEASE_ENTER_CHART_NAME_FIRST=Please enter chart name first. //js-> sharechartpublicly-js.asp
CHART_NAME_IS_AVAILABLE=Chart name is available. //js-> sharechartpublicly-js.asp
CHART_NAME_IS_NOT_AVAILABLE=Chart name is not available. //js-> sharechartpublicly-js.asp

