/*Here Constant vaiables are Declared */
var LAGNA_CHART = 0, NAVAMSA_CHART = 5, RASHI_FONT_SIZE = 13, PLANAT_FONT_SIZE = 15, HINDI_PLANAT_FONT_SIZE = 16
var CHART_NORTH = 0, CHART_SOUTH = 1, LARGEST_FONT_SIZE = 18;
var LANGUAGE_ENGLISH = 0, LANGUAGE_HINDI = 1, NORMAL_PLANET = 0, COLOR_INFO = 0;