

	 PLEASE_ENTER_EMAIL_ADDRESS							= Please enter email address
	 EMAIL_ADDRESS_ALREADY_ASSOCIATED_WITH_OTHER_ACCOUNT	= Email address already associated with other account.
	 EMAIL_ID_HAS_BEEN_UPDATED_SUCCESSFULLY				= Email Id has been updated successfully.
	 EMAIL_ID_UPDATION_FAILED								= Email Id updation failed.
	 NOT_YET_VERIFIED										= your email id is not yet verified. Please
	 DONOT_RECEIVED_EMAIL									= Didn't receive activation email on your email Id?
	 GO_TO													= go to 
	 TO_COMPLETE_THE_SIGN_UP_PROCESS						=  to complete the sign-up process.
	 RESEND_EMAIL											= Resend Email
	 AUR													= OR                        
	 CHANGE_EMAIL_ADDRESS									= Change Email Address
	 CURRENT_EMAIL											= Current Email
	 NEW_EMAIL												= New Email
	 ENTER_NEW_EMAIL_ADDRESS								= Enter a new email address
	 CHANGE_EMAIL											= Change Email
	 SENT_ON                                               = 
	 CLICK_HERE_FOR_LOGIN_HINDI                            = 
	 OPEN_LOGIN_PAGE                                       =  to open login page
