

	 ASTROSAGE_ONLINE_SHOPPING_STORE	= AstroSage Online Shopping Store
	 YANTRAS							= Yantras
	 YANTRAS_DATA						= Take advantage of Yantra with assurance of AstroSage.com
	 GEMSTONES							= Gemstones
	 GEMSTONES_DATA					    = Best quality gemstones with assurance of AstroSage.com
	 RUDRAKSH							= Rudraksh
	 RUDRAKSH_DATA						= Best quality Rudraksh with assurance of AstroSage.com
