
ANALYSIS_INTER = Analysis & Interpretations:
HEADERTEXT =   The @@FIRST$ houses should be analyzed to answer above-mentioned query.Your stars and other influencing factors as per the given details :- Gender: @@GENDER$, DOB: @@DOB$, TOB (24 Hour Format): @@TOB$, Place: @@PLACE$, Nearest Place: @@NPLACE$ indicates that,
FIRST = first
SECOND = second
THIRD = third
FOURTH = fourth
FIFTH = fifth
SIXTH = sixth
SEVENTH= seventh
EIGHTH = eighth
NINTH= ninth
TENTH = tenth
ELEVENTH = eleventh
TWELFTH = twelfth
SIGN_CHAR_SENTENCE = Moreover, your inner talents are @@charac$, try to enhance your skills and this will be useful for your overall progress.
ASCSIGNTEXT = Your ascendant is @@asc$ and your Moon Sign is @@moonsign$. @@asclord$ is the lord of @@asc$ & @@moonsignlord$ is the lord of @@moonsign$.
WISHES = All the best and stay blessed.
MALE = male
FEMALE = female
 