
SUBMIT= Submit
USE_EXCEPTION = Use Exception
NOTE_ARUDHA=  Note:- Here we are not considering Rahu and Ketu Stronger
ARUDHA_CHART= Arudha Chart
NOTE_JHORA = Sri Jagannath Center recommends using these exceptions,Whil Sri K N Rao does not recommend them.
NOTE_JHORA_ASTRO = Sri K N Rao school do not recommend using exceptions, while many others use exceptions. We at AstroSage, recommend using exceptions. 
DO_NOT_USE = Do not use exceptions