
ANNANT_KALSARPA_YOGA = Annant Kalsarpa Yoga
KULIK_KALSARPA_YOGA = Kulik Kalsarpa Yoga
VASUKI_KALSARPA_YOGA = Vasuki Kalsarpa Yoga
SHANKPAAL_KALSARPA_YOGA = Shankpaal Kalsarpa Yoga
MAHAPADAM_KALSARPA_YOGA = Mahapadam Kalsarpa Yoga
TAKSHAK_KALSARPA_YOGA = Takshak Kalsarpa Yoga
KARKOTAK_KALSARPA_YOGA = Karkotak Kalsarpa Yoga
SHANKACHOOD_KALSARPA_YOGA = Shankachood Kalsarpa Yoga
GHATAK_KALSARPA_YOGA = Ghatak Kalsarpa Yoga
VISHDHAR_KALSARPA_YOGA = Vishdhar Kalsarpa Yoga
SHESHNAG_KALSARPA_YOGA = Sheshnag Kalsarpa Yoga
PADAM_KALSARPA_YOGA = Padam Kalsharp Yoga