
	YOUR_RASHI_NAME_IS												= Your Rashi (Sign) name is
	DOT																= .
	YOUR_NAKSHATRA_NAME_IS											= Your Nakshatra Name is 
	AND_YOU_ARE_BORN_IN												= and you are born in
	CHARAN_PADA_OF_THE_NAKSHATRA										= Charan (Pada) of the Nakshatra.
	BASED_ON_IT_ASTROSAGE_COM_OFFERS_FOLLOWING_SUGGESTIONS_FOR_NAME	= Based on it, AstroSage.com offers following suggestions for name:
	FIRST_LETTER_OF_NAME_IN_ROMAN_ACCORDING_TO_YOUR_SIGN				= First letter of name (in roman) according to your sign:
	NO_SUGGESTIONS_AVAILABLE											= No Suggestions Available
	MEANING															= Meaning
	THESE_ARE_JUST_APPROXIMATE_SUGGESTIONS_PLEASE_ENSURE_THAT_THE_NAME_SOUND_START_WITH_THE_FIRST_LETTER_GIVEN_ABOVE = These are just approximate suggestions. Please ensure that the name sound start with the 'first letter' given above.


	FIRST_CHARAN														= first
	SECOND_CHARAN														= second
	THIRD_CHARAN														= third
	FOURTH_CHARAN														= fourth
