
     PREDICTIONS_AND_FREE_REPORTS					= Predictions & Free Reports
	 VARSHPHAL_PREDICTION							= Varshphal Prediction
	 CHARACTER_HOROSCOPE							= Character Horoscope
	 PRINT_CHART									= Print Chart
	 DOWNLOAD_PRINT_DETAILED_KUNDLI_IN_PDF_FORMAT	= Download / Print Detailed Kundli in PDF Format
	 ASK_OUR_ASTROLOGERS							= Ask Our Astrologers
