	
	BH_BUY_HDG							= Buy AstroSage Big Horoscope
	BH_TAG_TEXT							= 100+ Pages Horoscope
	BH_SERVICE_PRICE						= <b>Price:</b> <strike>Rs. 1105/-</strike> <b>Rs. 650/-</b>
	BH_PRINT_PRICE						= <b>Price:</b> <strike>Rs. 2101/-</strike> <b>Rs. 999/-</b>
	BH_DESC								= <b>What will you get in 100+ pages Big Horoscope:</b> Detailed predictions on marriage, career, finance, health, children, property, family etc. Dasha analysis for life. Varshphal for 10 years. Favorable period for marriage, career, business. Gemstones and Remedies. Sade-sati, Kaal Sarp, Mangal dosha. Bhav Phal and Graha Phal. Detailed calculations - Parashari, KP, Lal Kitab.
	BH_SAMPLE								= Sample
	BH_PDF_ONLY							= PDF Only
	BH_PRINTED							= Printed
	BH_INST_DELIVERY						= Instant Delivery
	BH_7DAY_DELIVERY						= Delivery in 7 Days
	BH_BUY_NOW							= BUY NOW
	BH_SMP_IMG							= vedic-report-en
