

	 VIMSHOTTARI_MAHADASHA_PHAL_DASHA_PREDICTIONS	= Vimshottari Mahadasha Phal
	 VIMSHOTTARI_MAHADASHA_PHAL_DASHA_PREDICTIONS_MASTROSAGE	= Vimshottari Mahadasha Phal (Dasha Predictions)
	 MAHADASHA_PHAL								= Mahadasha Phal
	 DASHA_PHALA_FULL_PREDICTION_ONE   = Your @@planetName$ is in @@rashiName$ sign which is a @@planetRelationship$ sign for @@planetName$. @@planetName$  is lord of @@houseAspects$ house and situated in @@houseNo1$ house. @@planetName$ aspects@@houseNo2$ house.
	 DASHA_PHALA_FULL_PREDICTION_TWO	= Your @@planetName$ is in @@rashiName$  sign which is a @@planetRelationship$ sign for @@planetName$. @@planetName$  is lord of @@houseAspects$ house and situated in @@houseNo1$ house. @@planetName$ aspects @@houseNo2$ house and aspected by @@AspectsPlanetName$
	 DASHA_PHALA_FULL_PREDICTION_THREE = Your @@planetName$ is in @@rashiName$ sign. @@planetName$ is situated in @@houseNo1$ house. @@planetName$ aspects @@houseNo2$ house.
	 DASHA_PHALA_FULL_PREDICTION_FOUR  = Your @@planetName$ is in @@rashiName$ sign. @@planetName$ is situated in @@houseNo1$ house.@@planetName$ aspects @@houseNo2$ house and aspected by @@AspectsPlanetName$
