
	GEMSTONE_PREDICTION				= Gemstone Prediction
	WHAT_IS_GEMESTONES				= What Is Gemstone?
	GEMINTRO							= The primary use for gems throughout history has been for healing and spiritual rituals. Although gems were rare and exhibited great beauty, the reason they were so precious was due to the power they imparted to their wearers. They are storehouses of empowerment, transmitted through contact with one's body. Gems exhibit their power in a beneficial or detrimental way - depending on how they are used. All stones or gems have magnetic powers in varying degrees, and many of them are beneficial to us for their therapeutic cures. They emit vibrations and frequencies which have strong potential influence on our whole being. Here's what your Gemstone prediction looks like.
	STONE_DESCRIPTION					= A life stone is a gem for the Lagna lord. One can wear it all though his life to experience it's mystic powers. Wearing a life stone can remove obstacles and bless an individual with happiness, success and prosperity. It is generally worn to bring about an overall well being of an individual. It's cosmic rays are influence his entire existence.#Life is a perfect blend of efforts and destiny. Get destiny to work for you by wearing you're lucky stone. An individual's lucky stone is one that keeps luck ticking bringing in pleasant surprises in life. The Lucky stone we recommend for you is:#Recommendations of Bhagya stone also known as fortune stone is done on the basis of the Lord goverining the ninth house.This stone is known to make fortune work for you when you actually need it.Good fortune comes your way in personal and professional life .It helps you combat any obstacle that stands in your way of prosperity.
	QUALITIES2						= 2 Carats
	QUALITIES3						= 3 Carats
	QUALITIES3P						= 3 Carats
	QUALITIES1						= 1 Carats
	QUALITIES1_5						= 1.5 Carats
	GOLD_IN_RING_FINGER				=  Gold, in ring finger
	SILVER_IN_RING_FINGER				=  Silver, in ring finger
	GOLD_OR_SILVER_IN_RING_FINGER		=  Gold (pref. 18 Carats) or Silver, in ring finger
	GOLD_IN_RING_OR_FINGER			=  Gold, in ring or little finger
	GOLD_IN_INDEX_FINGER				=  Gold, in index finger
	GOLD_OR_SILVER_IN_MIDDLE_FINGER	=  Gold or silver in middle finger
	GOLD_IN_MIDDLE_FINGER				=  Gold, in middle finger
	SUN_MANTRA						= Om hram hrim hraum sah suryaya namah
	MOON_MANTRA						= Om shram shrim shraum sah chandraya namah
	MAR_MANTRA						= Om kram krim kraum sah bhaumaya namah
	MER_MANTRA						= Om bram brim braum sah budhaya namah
	JUP_MANTRA						= Om gram grim graum sah gurave namah
	VEN_MANTRA						= Om dram drim draum sah shukraya namah
	SAT_MANTRA						= Om pram prim praum sah shanaisharaya namah
	RAH_MANTRA						= Om bhram bhrim bhraum sah rahave namah
	KET_MANTRA						= Om sram srim sraum sah ketave namah
	RECOMMEND_GEMESTONES				= Recommend Gemstone
	QUALITIES_OF_THE_GEMSTONE			= Minimum Recommended Weight
	WEARING_INSTRUCTIONS				= Wearing instructions
	RECOMMEND_MANTRA					= Recommend Mantra
	IMPORTANT_INFORMATION				= Important Information
	IMPORTANT_INFO					= <p>While wearing a gem please keep certain things in mind. Purchase only original gemstones as wearing those that are not original will have no effect. You also need to wear the prescribed weight, what is commonly known as "Ratti". Now days markets are flooded with fake gems. To give our readers genuine assistance AstroCAMP/ AstroSage brings to you our unique genuine collection of Gemstones. To know more about it click here.</p> <p><b>To buy Gemstones, please <a href=http://www.astrocamp.com/products.asp><u>check out our Gemstones Astro Shop</u></a></b>.</p> <p><b>To order your "Gemstones Recommendations" by our expert astrologers, please visit <a href=http://www.astrocamp.com/service.asp?service_id=84&prtnr_id=1><u>Gemstones Recommendations page</u></a></b>.</p>
	YOUR_LIFE_STONE					= Life Stone
	YOUR_LUCKY_STONE					= Lucky Stone
	YOUR_BHAGYA_STONE					= Bhagya Stone
	RECOMMENDATION					= Recommendation
