
    PERSON											= Person 
	MANGLIK											= Manglik 
	PERSON_IS_MANGLIK									= Person is Manglik
	PERSON_IS_NOT_MANGLIK								= Person is not Manglik
	MANGLIK_DETAILS_PARAGRAPH1						= Generally Manglik Dosha is considered from the position of Lagna and Moon in the birth chart.
	MANGLIK_DETAILS_FIRST								= In the birth chart, Mangal is placed in 
	MANGLIK_DETAILS_SECOND							=  house from Lagna, while in the Moon chart Mangal is placed in 
	MANGLIK_DETAILS_THIRD								=  house.
	MANGLIK_DETAILS_HENCE_NOTE						= Hence Mangal Dosha is 
	PRESENT_NEITHER_IN_LAGNA_CHART_NOR_IN_MOON_CHART	=Hence Mangal Dosha is present neither in Lagna Chart nor in Moon Chart.
	MANGLIK_DETAILS_HENCE_NOTE1						= Hence Mangal Dosha is present in Lagna Chart as well as Moon Chart.
	MANGLIK_DETAILS_HENCE_NOTE2						= Hence Mangal Dosha is present in Lagna Chart but not in Moon Chart.
	MANGLIK_DETAILS_HENCE_NOTE3						= Hence Mangal Dosha is not present in Lagna Chart while present in Moon Chart.
	MANGLIK_DETAILS_PARAGRAPH4						= Mangal Dosha is considered to create hurdles in the married life of a person. According to some, Mangal Dosha results in frequent illness or ultimately death of partner(s).
	MANGLIK_DETAILS_PARAGRAPH5						= It is considered that if a manglik person marries to another manglik person then the manglik dosha gets cancelled and has no effect.
	MANGLIK_DETAILS_SUBHEADING1						= Some Remedies (in case Mangal Dosha is present)
	MANGLIK_DETAILS_SUBHEADING2						= Remedies (needs to be performed before marriage)
	MANGLIK_DETAILS_SUBHEADING3						= Remedies (can be performed after marriage)
	MANGLIK_DETAILS_PARAGRAPH6						= Kumbha Vivah, Vishnu Vivah and Ashwatha Vivah are the most popular remedies for Mangal Dosha. Ashwatha vivaha means the marriage with peepal or banana tree and cutting the tree after that. Kumbha Vivah, also called Ghata Vivaha, means marriage with a pot and breaking it after that.
	REMEDIES1											= Keep Kesariya Ganapati (Orange coloured idol of Lord Ganesha) in worship room and worship daily. 
	REMEDIES2											= Worship Lord Hanuman by reciting Hanuman Chalisa daily.
	REMEDIES3											= Mahamrityunjaya paath (recitation of Mahamrityunjaya mantra).
	MANGLIK_DETAILS_SUBHEADING4						= Remedies (based on Lal Kitab, can be performed after marriage)
	LK_REMEDIES1										= Feed birds with something sweet. 
	LK_REMEDIES2										= Keep ivory (Haathi Daant) at home.
	LK_REMEDIES3										= Worship banyan tree with milk mixed with something sweet.
	MANGLIK_DETAILS_NOTE								= We strongly recommend you to consult an astrologer before performing these remedies by your own.
