
	MATCH_ME												= Match My Horoscope
	ENTER_GIRLS_BIRTH_DETAILS								= Enter Girl's birth details
	ENTER_BOYS_BIRTH_DETAILS								= Enter Boy's birth details
	MATCH_WITH_PUBLIC_CHART								= Match with Public Chart
	ENTER_GIRLS_DETAILS									= Enter Girl's Details
	ENTER_BOYS_DETAILS									= Enter Boy's Details
	ENTER_GIRLS_CHART_NAME								= Enter girl's chart name
	ENTER_BOYS_CHART_NAME									= Enter boy's chart name

	UNKNOWN_ERROR_OCCURRED								= Unknown Error Occurred. 
	THERE_IS_NO_SAVED_CHART								= There is no saved chart. 

	YOU_ARE_NOT_LOGIN_OR_YOUR_SESSION_HAS_BEEN_EXPIRED	= You are not login or your session has been expired. 
	PLS_ENTER_CHART_NAME									= Please enter chart name. 
	CHART_NAME_DOES_NOT_EXIST								= Chart name does not exist.
	DO_NOT_FIND_CHART_NAME								= Do not find Chart name. '
	SOME_ERR_OCCRR_IN_PROCESSING_YOUR_QRY_PLS_AGAIN		= Error occurred in processing your query. Please try again. 
	SESSION_TIME_OUT_MSG									= Your session has been expired. Please Login again.
	CLICK_RADIO_MATCH_DETAILS = Click on the radio button in front of the person with who you want to match your horoscope.<br/><br/>
	MATCH_HOROSCOPE_SHARED_CHART = You can match a horoscope with a shared (public) chart here. Enter your partner's chart name in the text box below. Please note that Partner's chart name must be public in order to use this feature.<br /><br />For example, if you are a boy and want to match your kundli with Katrina Kaif's shared chart, enter <b>Katrina</b> below.<br /><br />  
