	WHAT_IS_MOON_SIGN = What is Moon Sign?
	MOON_SIGN_INTRO	= Vedic astrology gives more importance to the Moon Signs than the Sun signs for horoscopes. In fact, Vedic astrology declares that the Moon sign should be treated as the center of birth chart in place of ascendant or rising sign, in case the Moon is stronger than the ascendant. Moon Sign horoscopes reveals many hidden secrets of personality which cannot be disclosed by Sun signs. 
	MOON_SIGN_FOR = Moon Sign
	HOME = Home
	MOON_SIGN_CALCULATOR = Moon Sign Calculator
	MOON_SIGN = Moon Sign
	BASED_BIRTH_DETAILS = Based on the provided birth details.
	DYNAMIC_HEALTH_MOON_SIGN = Health For @@signname$ Moon Sign
 	DYNAMIC_TEMP_PERSONALITY_MOON_SIGN = Temperament & Personality For @@signname$ Moon Sign
 	DYNAMIC_PHYSICAL_APPEARANCE_MOON_SIGN = Physical Appearance For @@signname$ Moon Sign
	DAILY_HOROSCOPE = Daily Horoscope
	WEEKLY_HOROSCOPE = Weekly Horoscope
	MONTHLY_HOROSCOPE = Monthly Horoscope
	CHARACTERISTICS = Characteristics
	LOVE_HOROSCOPE = Love Horoscope
	YEARLY_HOROSCOPE = Yearly Horoscope