
	ENTER_YOUR_BIRTH_DETAILS										= Enter Your Birth Details 
	PLEASE_DO_NOT_ENTER_SPECIAL_CHARACTERS_SIGN_IN_NAME_FIELD		= Please do not enter  \\'(single quote)\\' , ? (question mark),& (ampersand) sign in name field. 
	PLEASE_DO_NOT_ENTER_MORE_THAN_50_CHARACTER_IN_NAME_FIELD		= Please do not enter more than 50 character in name field.
	PLEASE_DO_NOT_ENTER_SPECIAL_CHARACTERS_SIGN_IN_PLACE_FIELD	= Please do not enter \\'(single quote)\\' , ? (question mark),& (ampersand) sign in place field. 
	PLEASE_ENTER_A_VALUE_FOR_THE_KP_HORARY_FIELD					= Please enter KP Horary number value 
	THE_VALUE_FOR_KP_HORARY_SHOULD_BE_BETWEEN_0_AND_249			= The value for KP Horary number should be between 0 and 249 
