
MIN_3_CHAR                                                    = Min. 3 characters
N_C_LAHIRI                                                    = N.C.Lahiri
B_V_RAMAN                                                     = B.V.Raman
T_24_HOUR_FORMAT                                              = 24 hours format

