
MANAGE_CHART=Manage Chart
CURRENT_OPEN_CHART_CANT_BE_DELETE=You can not delete the currently opened chart.
ARE_YOU_SURE_THAT_YOU_WANT_TO_DELETE_THE_CHART_OF=Are you sure that you want to delete the chart of 
CHART_DELETE_FOR_HINDI=?
CHART_HAS_BEEN_DELETED_SUCCESSFULLY=Chart has been deleted successfully.
CHART_NOT_DELETED=Chart not deleted.
ERROR_OCCURRED=Error Occurred. Please try again after some time
MORE_CHART=More Charts
OPENN=Open
DELETE=Delete
YOU_ARE_NOT_AUTHORIZE=You are not authorized to view this page
OPEN_CHART_SEARCH=Open Chart (By Search)
OPENCHART=Open Chart
