 
PRASTHARASHTAKVARGA_TABLES	= Prastharashtakvarga 
SIGNIFICATOR = Significator
INDICATOR = Indicator
AUSPICIOUS =  Auspicious
INAUSPICIOUS = Inauspicious
MIXED = Mixed
FATHER = Father
GOVERNMENT = Government
HEALTH = Health
MOTHER = Mother
MIND = Mind
EYE = Eye
SIBLINGS = Siblings
COURAGE = Courage
PROPERTY = Property
BUSINESS = Business
INTELLIGENCE = Intelligence
EDUCATION = Education 
CHILDREN = Children
KNOWLEDGE = Knowledge
MONEY = Money
RELIGION = Religion
GRANDEUR = Grandeur
SPOUSE = Spouse
LUXURY = Luxury
MARRIAGE = Marriage
EMPLOYMENT = Employment
AGE = Age
SERVENT = Servant
LONGEVITY = Longevity
VEHICLE = Vehicle 