
 CHANGES_SAVED_SUCCESSFULLY = Chart shared successfully
 CHANGES_NOT_SAVED = Chart not shared. Please try again.
 CHART_NAME_CAN_NOT_BE_START_WITH_DIGIT_HYPHEN = Chart name can not be start with digit or hyphen
 CHART_NAME_CAN_NOT_BE_END_WITH_HYPHEN = Chart name can not be end with hyphen
 PLEASE_ENTER_VALID_CHARTNAME = Please enter valid chart name
 PLEASE_ADD_EMAIL_ADDRESS = Please add email addresses 
