

	 TRANSIT_GOCHAR_TODAY							   = Transit(Gochar) Today
	 ASHTAKVARGA_POINTS_FOR_TRANSIT	                   = Ashtakvarga Point for Transit
	 AVPOINTS							               = AVPoints

	 JANMA											   = Janma
	 SAMPAT										      = Sampat
	 VIPAT											   = Vipat
	 KSHEMA										      = Kshema
	 PRETYERI										   = Pretyeri
	 SAADHAK										   = Saadhak
	 VADH											   = Vadh
	 MAITREE										   = Maitree
	 ADHI_MAITREE									   = Adhi-Maitree
     NOT_GOOD										   = Not Good
	 TOTALLY_BAD									   = Totally Bad
     TARA_RAMEDY_FIRST								   = Donate vegetables--Yellow Pumpkin,Leafy Vegetable
	 TARA_RAMEDY_SECOND							      = Donate jaggery
	 TARA_RAMEDY_FIFTH								   = Donate salt
	 TARA_RAMEDY_SEVENTH							   = Should be avoided. If inevitable Tila Sahita Suvrana Danam (Seseme seeds+Gold)
	 TARA_WITH_RAMEDIES_HEADING                       = Current  Tara	
	 RAMEDIES										   = Remedies	
	 KP_PLANETS									      = KP Planets								   


	
	
	
	
	
	
	
	
	
    
	
	
	
	
	
	
	
	
    
	
	
	

	