
	
	 SUN_SIGN_WESTERN			= Sun Sign (Western)
	 JANAM						= Janam (Birth)
	 VARSHA					= Varsha (Year)
	 VARSHAPHAL_CHART_TABLE	= Varshphal Chart & Table
	 VARSHAPHAL_CHART			= Varshphal Chart (Solar Return Chart)
	 VARSHAPHAL_TABLE			= Varshphal Table
	 MUNTHA					= Muntha
	 PUNYA						= Punya
	 POPULARITY_FAME			= Popularity & Fame
	 FATHER					= Father
	 MOTHER					= Mother
	 LIFE						= Life
	 KARNA						= Karna
	 DEATH						= Death
	 FOREIGN_TRAVELS			= Foreign Travels
	 ADULTERY					= Adultery
	 DISEASE					= Disease
	 ALTERNATE_VOCATION		= Alternate Vocation
	 TRADE						= Trade
	 KARYA_SIDDHI				= Karya Siddhi
	 MARRIAGE					= Marriage
	 PROGENY					= Progeny
	 BUSINESS					= Business
	 FOES						= Foes
	 IMPRISONMENT				= Imprisonment
	 FINANCIAL_GAINS			= Financial Gains
	 SAHAM						= Saham
	 MUDDA						= Mudda
	 FROM						= From

	 FROM_MASTROSAGE			= From: 

	 T							= To

	 T_MASTROSAGE			    = To: 

	 TRIRASHI					= Trirashi
	 DINRATRI					= DinRatri
	 PANCHADIKARI				= Panchadhikari
	 VARSHPRAVESH				= Varshpravesh
	 MUNTHA_IN_HOUSE			= Muntha In House
	 MUNTHA_IN_BIRTH_CHART		= Muntha In Birth Chart
	 VARSH						= Varsh
	 DETAILS					= Details
	 HEAD						= Head
	 PREDICTION				= Prediction
	 BHAV_NUMBER				= Bhav Number
	 EXTRAFORHINDI				= 
	 
	  LAGNALORD				= Lagna Lord
