

	 Vimshottari_MD_AD_HEADING			= 
	 Vimshottari_MD_AD_SERIES_HEADING	= 
	 Vimshottari_AD_PD_SD_HEADING		= 
	 Vimshottari_MD_AD				= Vimshottari MD & AD
	 Vimshottari_MD_AD_1				= Vimshottari AD & PD # 1
	 Vimshottari_MD_AD_2				= Vimshottari AD & PD # 2
	 Vimshottari_MD_AD_3				= Vimshottari AD & PD # 3
	 Vimshottari_MD_AD_4				= Vimshottari AD & PD # 4
	 Vimshottari_MD_AD_5				= Vimshottari AD & PD # 5
	 Vimshottari_AD_PD_SD_1			= Vimshottari AD & PD & SD # 1
	 Vimshottari_AD_PD_SD_2			= Vimshottari AD & PD & SD # 2
	 Vimshottari_AD_PD_SD_3			= Vimshottari AD & PD & SD # 3
	 Vimshottari_AD_PD_SD_4			= Vimshottari AD & PD & SD # 4

