

 GO_TO_ASTROSAGE_CLOUD                  = Go to AstroSage Cloud 
 LOGIN_TEXT                             = Only logged-in user can use worksheet. 
 WK_RESET                                  = Reset 


