DAY_VALUES=रविवार ÿ सोमवार ÿ मंगलवार ÿ बुधवार ÿ गुरूवार ÿ शुक्रवार ÿ शनिवार
DAYLRD_VALUES=  सूर्य ÿ चंद्र ÿ मंगल ÿ बुध ÿ गुरू  ÿ शुक्र ÿ्र शनि
DAY_TRIRASHIPATI=सूर्य ÿ शुक्र ÿ्र शनि ÿ्र शुक्र ÿ्र गुरू  ÿ चंद्र ÿ बुध ÿ मंगल ÿ शनि ÿ मंगल ÿ गुरू  ÿ चंद्र ÿ
NIGHT_TRIRASHIPATI= गुरू  ÿ चंद्र ÿ बुध ÿ मंगल ÿ सूर्य ÿ शुक्र ÿ्र शनि ÿ बुध ÿ शनि ÿ मंगल ÿ गुरू  ÿ चंद्र ÿ

RAS_VALUES= मेष ÿ वृष ÿ मिथुन ÿ कर्क ÿ सिंह ÿ कन्या ÿ तुला ÿ वृश्चिक ÿ धनु ÿ मकर ÿ कुंभ ÿ मीन
RASLRD_VALUES= मंगल ÿ शुक्र ÿ बुध ÿ चंद्र ÿ सूर्य ÿ बुध ÿ शुक्र ÿ मंगल ÿ गुरू  ÿ शनि ÿ शनि ÿ गुरू
NAKLRD_VALUES= केतु ÿ शुक्र ÿ सूर्य ÿ चंद्र ÿ मंगल ÿ राहु ÿ गुरू  ÿ शनि ÿ बुध
TIT_VALUES= प्रतिपद ÿ द्वितीया ÿ तृतिया ÿ चर्तुथी र्ÿ पंचमी ÿ षष्ठी ÿ सप्तमी ÿ अष्टमी ÿ नवमी ÿ दशमी ÿ एकादशी ÿ द्वादशी ÿ त्रयोदशी ÿ चतुर्दशी ÿ पूर्णिमा ÿ प्रतिपद ÿ द्वितीया ÿ तृतिया ÿ चर्तुथी र्ÿ पंचमी ÿ षष्ठी ÿ सप्तमी ÿ अष्टमी ÿ नवमी ÿ दशमी ÿ एकादशी ÿ द्वादशी ÿ त्रयोदशी ÿ चतुर्दशी ÿ अमावस्या
NAK_VALUES= अश्विनी ÿ भरणी ÿ कृतिका ÿ रोहिणी ÿ मृगशिरा ÿ आद्र्रा ÿ पुनर्वसु ÿ पुष्य ÿ आश्लेषा ÿ मधा ÿ पू0फाल्गुनी ÿ उ0फाल्गुनी ÿ हस्त ÿ चित्रा ÿ स्वाती ÿ विशाखा ÿ अनुराधा ÿ ज्येष्ठा ÿ मूल ÿ पूर्वाषाढा ÿ उ0षाढा ÿ श्रवण ÿ धनिष्ठा ÿ शतभिषा ÿ पूर्वाभाद्रपद ÿ उ0भाद्रपद ÿ रेवती
YOG_VALUES= विषकुम्भ ÿ प्रीति ÿ आयुष्मान ÿ स©भाग्य ÿ ाोभन ÿ अतिगण्ड ÿ सुक्रर्मा ÿ ध¤ति ÿ ाूल ÿ गण्ड ÿ वृि ÿ ध्रुव ÿ व्याघात ÿ हर्षण ÿ बैर ÿ सिि ÿ व्यतिपात ÿ वरीयान ÿ परिघ ÿ िाव ÿ सि ÿ साघ्य ÿ ाुभ ÿ ाुक्ल ÿ ब्रह्य ÿ इन्द्र ÿ वैधृति
X1_VALUES= केतु ÿ शुक्र्र ÿ सूर्य ÿ चंद्र ÿ मंगल ÿ राहु ÿ गुरू  ÿ शनि ÿ बुध
GRAHA_VALUES= लग्न ÿ सूर्य ÿ चंद्र ÿ मंगल ÿ बुध ÿ गुरू ÿ शुक्र ÿ  शनि  ÿ राहु ÿ केतु ÿ अरूण ÿ वरूण ÿ यम
BHAVANUM_VALUES=1 ÿ 2 ÿ 3 ÿ 4 ÿ 5 ÿ 6 ÿ 7 ÿ 8 ÿ 9 ÿ 10 ÿ 11 ÿ 12
KARAN_VALUES= किस्ं़़़तुध्न ÿ भाव ÿ बालव ÿ केोलव ÿतैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ भाव ÿ बालव ÿ केोलव ÿ तैेतिल ÿ गर ÿ वणिज ÿ विष्टि ÿ शकुन ÿ चतुष्पाद ÿ नागा
PAKSHA_VALUES=कृष्ण ÿ शुक्ल
DIV_VALUES= लग्न ÿ होरा ÿ दिृकाना ÿ चर्तुतम्सा ÿ सप्तमांश ÿ नवमांश ÿ दसमांश ÿ दादसमांश ÿ शोषशांश ÿ विमसामांश ÿ सप्तमांश ÿ चतुरमांश ÿ त्रिशांश ÿ खवेदांश ÿ अक्षवेदांश ÿ षष्ठियांश
MANGALDOSH_VALUES= नहीं ÿ कम ÿ मध्यम ÿ उच्च
VARNA_VALUES= ब्राहमण ÿ क्षत्रिय ÿ वैश्य ÿ शूद्र
YONI_VALUES= अश्व ÿ गज ÿ मेष ÿ सर्प ÿ श्वान ÿ विलाव ÿ मूषक ÿ गउ ÿ महिष ÿ व्याध ÿ मृग ÿ वानर ÿ नकुल ÿ सिंह
GANA_VALUES= देव ÿ मानव ÿ राक्षस
VASYA_VALUES= चतुष्पद ÿ मानव ÿ जलचर ÿ वनचर ÿ कीट ÿ पता-नहीं
VASHYA_VALUES= चतुष्पद ÿ मानव ÿ जलचर ÿ वनचर ÿ कीट
NADI_VALUES= आदि ÿ मध्य ÿ अन्त
ARRNADI_VALUES= आदि ÿ मध्य ÿ अन्त
TARA_VALUES= जन्म ÿ सम्पत ÿ विपत ÿ क्षेम ÿ प्रत्यय ÿ साधक ÿ वध ÿ मित्र ÿ अतिमित्र
PAYA_VALUES= स्वर्ण ÿ रजत ÿ ताम्र ÿ लोह
DEB_VALUES=शनि ÿ --- ÿ केतु ÿ मंगल ÿ --- ÿ शुक्र केतु ÿ सूर्य ÿ मंगल ÿ राहु	 ÿ गुरु ÿ --- ÿ बुध राहु	
EXAL_VALUES= सूर्य ÿ चन्द्र ÿ राहु ÿ गुरु ÿ --- ÿ बुध राहु ूÿ शनि ÿ --- ÿ केतु ÿ मंगल ÿ --- ÿ शुक्र केतु
ASPECTS_VALUES= शून्य ÿ स्वास्थ्य ÿ वित्त ÿ परिवार ÿ प्रेम ÿ वैवाहिक जीवन ÿ व्यवसाय
PLANETNAMEVIM_VALUES= केतु ÿ शुक्र ÿ सूर्य ÿ चन्द्र ÿ मंगल ÿ राहु ÿ गुरु ÿ शनि ÿ बुध
PLANETNAME_VALUES= सूर्य ÿ चन्द ÿ मंगल ÿ बुध ÿ गुरु ÿ शुक्र ÿ शनि ÿ राहु ÿ केतु
OUTCOMES_VALUES= बहुत बुरा ÿ बुरा ÿ मध्यम बुरा ÿ मध्यम अच्छा ÿ अच्छा ÿ बहुत अच्छा
ARRGANA_VALUES= देव ÿ मानव ÿ राक्षस
GRAHANAME_VALUES= सूर्य ÿ चन्द्र ÿ मंगल ÿ बुध ÿ गुरु ÿ शुक्र ÿ शनि
X9_VALUES= केतु ÿ शुक्र्र ÿ सूर्य ÿ चंद्र ÿ मंगल ÿ राहु ÿ गुरू  ÿ शनि ÿ बुध
AREAOFLIFE_VALUES=कार्यक्षेत्र ÿ आधिपत्य ÿ भाग्य ÿ मानसिकता ÿ सामंजस्य ÿ गुण ÿप्रेम ÿ स्वास्थ्य
RAS1_VALUES= मेष ÿ वृष ÿ मिथुन ÿ कर्क ÿ सिंह ÿ कन्या ÿ तुला ÿ वृश्चिक ÿ धनु ÿ मकर ÿ कुंभ ÿ मीन
YOGINI_NAME_IN_FULL_VALUES= मंगला ÿ पिंगला ÿ धनिया ÿ भ्रमरी ÿ भद्रिका ÿ उल्का ÿ सिद्धा  ÿ संकटा
LORD_OF_YOGINI=चंद्र ÿ सूर्य ÿ  गुरू ÿ मंगल ÿ बुध ÿ  शनि  ÿ शुक्र ÿ राहु 
YOGINI_VALUES=मं ÿ पिं ÿ  ध ÿ भ्र ÿ भद्रि ÿ उल् ÿ सि ÿ सं
DAY_CHOGHADIA_VALUES= उद्वेग ÿ चल ÿ लाभ ÿ अम्रत ÿ काल ÿ शुभ ÿ रोग
NIGHT_CHOGHADIA_VALUES=शुभ ÿ अम्रत ÿ चल ÿ रोग ÿ काल ÿ लाभ ÿ उद्वेग
ASPECT_VALUES=युति  ÿ  पंच ÿ तृती ÿ नवां ÿ अष्टा ÿ सप्त ÿ चतृर्थ ÿ अर्धद्वितीय ÿ पंचा ÿ पष्ठ

JAAGRAT_VALUES= जाग्रत ÿ स्वप्न ÿ सुसुप्त
BALADI_VALUES=बाल ÿ कुमार ÿ युवा ÿ वृद्ध ÿ मृत
DEEPTA_VALUES=शान्त ÿ दीप्त ÿ खल ÿ स्वत ÿ मुदित ÿ दीन ÿ पीड्य ÿ सक्त ÿ विकल ÿ भीत
KARAKA_VALUES=आत्म ÿ अमात्य ÿ भ्रातृ ÿ मातृ ÿ पुत्र ÿ ग्नति ÿ दारा
KISMAT_VALUES= मंगल ÿ चन्द्र ÿ बुध ÿ चन्द्र ÿ सूर्य ÿ केतु ÿ शुक्र ÿ चन्द्र ÿ शनि ÿ शनि ÿ गुरु ÿ राहु 
MAALIK_VALUES= मंगल ÿ शुक्र ÿ बुध ÿ चन्द ÿ सूर्य ÿ बुध ÿ शुक्र ÿ मंगल ÿ गुरु ÿ शनि ÿ शनि ÿ गुरु
PAKKA_GHAR_VALUES= सूर्य ÿ गुरु ÿ मंगल ÿ चन्द्र ÿ गुरु ÿ बुध केतु ÿ शुक्र बुध ÿ मंगल शनि ÿ गुरु ÿ शनि ÿ शनि ÿ गुरु राहु 
#Key Fields
AYAN_KEY=लाहिरी
YR_STRING_KEY=वर्ष
YEARS_STRING_KEY= वर्ष
 
HR_STRING_KEY=घन्टा
HOUR_STRING_KEY=घन्टा
ENT_TIME_STRING_KEY=प्रवेश काल
DAY_STRING_KEY=दिन
NIGHT_STRING_KEY=रात
EXIT_TIME_STRING_KEY=निकास काल
PLANET_STRING_KEY=ग्रह
DAY_LORD_STRING_KEY=दिन का स्वामी
RAHUKAAL_STRING_KEY= राहु काल
AM_STRING_KEY=प्रातः
PM_STRING_KEY=रात्रि
TO_STRING_KEY=से
YOGINI_MAHA_DASA_STRING_KEY=योगिनी महादशा









